version: '3.1'

services:

  # BACKEND
  backend:
    build: ./backend
    env_file:
      - .env
    command: daphne scrummage.asgi:application --bind 0.0.0.0 --port 8000
    volumes:
      - /volumes/logs/backend:/logs/
      - /volumes/media:/media/
      - /volumes/static:/static/
    depends_on:
      - redis
    restart: always

  # LOAD BALANCER
  proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /volumes/nginx/ssl:/etc/nginx/ssl
      - /volumes/media:/media/
      - /volumes/static:/static/
      - /volumes/logs/proxy:/var/log/nginx/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /volumes/logs:/logs/
    depends_on:
      - backend
    restart: always

  # MAIL SERVER
  mailserver:
    image: natoora/postfix
    volumes:
      - /volumes/logs/mailserver/:/var/logs/
    restart: always

  # REDIS
  redis:
    image: redis
    restart: always

  # CELERY WORKER
  celery_worker:
    build: ./backend
    command: celery -A scrummage worker --loglevel=INFO
    volumes:
      - /volumes/celery:/celery/
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    restart: always

  # CELERY BEAT
  celery_beat:
    build: ./backend
    command: celery -A scrummage beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - /volumes/celery:/celery/
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    restart: always
