# Generated by Django 3.1.7 on 2021-04-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trelloboard',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trellocard',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trellolabel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trellolist',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
